version: '3.5'

services:
  app:
    image: nelsonfrank/shopkeeper-api:main
    container_name: shopkeeper-api
    environment:
      ENV: production
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src