version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shopkeeper-api
    environment:
      ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src